### ISSUE TITLE
Using custom network name for OpenIMS

### ISSUE THREAD

**Issue by rajdeepwalia** [openbaton/openimscore-packages#6]
Hi,

Today the network name used for OpenIMS deployment using Openbaton is hardcoded to'mgmt' and using a network with different network name is not possible.

I have done some changes in the scripts and Generic VNFM code in order to accept any network name for deploying OpenIMS using Openbaton. 

Best regards,
Rajdeep Ahluwalia

**Comment by gc4rella** [comment]
Hi, could you please be more precise about the changes needed to the generic VNFM code? At the moment, it is true that the OpenIMSCore on marketplace are containing static network names, however the NFVO/VNFM supports any network names. Therefore, you can download the NSD locally, modify and on board it yourself, if you need to modify network names.

**Comment by gc4rella** [comment]
without any further input, I consider this issue resolved.
